spring.datasource.url=jdbc:oracle:thin:@qrw.ars:1521:QR10
spring.datasource.username=api
spring.datasource.password=htrhtfwbz
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

logging.level.com.example.oracleapi=DEBUG

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Barnaul

max.api.verification-token=Lwc9r3qpr7YkVp1Tov-36lGPjOd3ICKMRmkLVeC04E7vSRZ1vJVjp30LQxGHh8doT4SsSBuyySA
max.api.bot-call-token=f9LHodD0cOIc8-bj38JLYZFUZ2lQ5MSIOWGDAQVPQbuE-ws1bku2rcWZZoU9CrRk7WCeXBqZ_ZdxTeFYiaqq
max.api.bot-auth-token=f9LHodD0cOKveOeBMAqL74EIO8CTAVDXaH8nGCNrOkgK0PwO2DxOty8pralEsOTYCpS_ydHnRrVlObicPzzv



# Asterisk AMI
asterisk.ami.username=kotlin_service_dev
asterisk.ami.secret=rfhyfdfk