spring.datasource.url=jdbc:oracle:thin:@qrlw.ars:1521:QR10
spring.datasource.username=api
spring.datasource.password=htrhtfwbz
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

app.host=qrlw.ars
app.name=API ??????? (????)

logging.level.com.example.oracleapi=WARN