spring.application.name=OracleAPI
spring.datasource.url=jdbc:oracle:thin:@qrlw.ars:1521:QR10
spring.datasource.username=api
spring.datasource.password=htrhtfwbz
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=250
jwt.secret=abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234
#???? ????? ?????? 14 ?????
jwt.expiration=50400000
jwt.secure=false
jwt.cookieName=accessToken