spring.datasource.url=jdbc:oracle:thin:@qrlw.ars:1521:QR10
spring.datasource.username=api
spring.datasource.password=htrhtfwbz
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

logging.level.com.example.oracleapi=WARN
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Barnaul

max.api.verification-token=Lwc9r3qpr7YkVp1Tov-36lGPjOd3ICKMRmkLVeC04E7vSRZ1vJVjp30LQxGHh8doT4SsSBuyySA
max.api.bot-token=f9LHodD0cOKenCqRJ4ITIZisdC-YlxxC9k8ctF2r9USZ2D4J4imjggDy7dnM-e0rO3FzonqbBVjmFbhzzKrK

asterisk.ami.username=kotlin_service_prod
asterisk.ami.secret=rfhyfdfk