spring.application.name=OracleAPI

spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=20
spring.task.execution.pool.queue-capacity=250

jwt.secret=abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234
jwt.expiration=50400000
jwt.secure=false
jwt.cookieName=accessToken

logging.charset.console=UTF-8
logging.charset.file=UTF-8

spring.profiles.active=dev

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB