knife4j:
  enable: true
  setting:
    language: en
    enable-group: true
    enable-swagger-models: false
  documents:
    - group: main-api
      name: Документация
      locations: classpath:markdown/*
    - group: main-api
      name: Описание
      locations: classpath:markdown/description/*
    - group: main-api
      name: GitLab
      locations: classpath:markdown/gitlab/*
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    groups-order: asc
    try-it-out-enabled: true
  show-actuator: false
  group-configs:
    - group: auth
      display-name: Авторизация
      paths-to-match:
        - /v1/auth/**
    - group: oracle-packages
      display-name: Пакеты Oracle
      paths-to-match:
        - /v1/pictures/**
        - /v1/public/**
        - /v1/email/**
    - group: 1c-packages
      display-name: API 1C
      paths-to-match:
        - /v1/api/1c/**
    - group: mark
      display-name: Маркировка
      paths-to-match:
        - /v1/mark/**