package com.example.oracleapi.dto.agn

import com.example.oracleapi.entity.table.AgnList
import java.time.LocalDateTime

data class AgnListForUpdResponse(
    val rn: Long,
    val agncode: String? = null,
    val agnname: String? = null,
    val agnidnumb: String? = null,
    val reasonCode: String? = null,
    val agntype: Long? = null,
    val addrFactpost: String? = null,
    val addrUrpost: String? = null,
    val phone: String? = null,
    val phonenumberrn: Long? = null,
    val fax: String? = null,
    val mail: String? = null,
    val bankaccname: String? = null,
    val bankaccnumb: String? = null,
    val bankaccbik: String? = null,
    val bankacckor: String? = null,
    val passportSer: String? = null,
    val passportNumb: String? = null,
    val passportWhen: LocalDateTime? = null,
    val passportWho: String? = null,
    val agnContacts: String? = null,
    val agngroup: Long? = null,
    val manager: Long? = null,
    val typecard: Long? = null,
    val business: String? = null,
    val licence: String? = null,
    val enabled: Long? = null,
    val cashlessDelay: Long? = null,
    val cashlessCredit: Double? = null,
    val note: String? = null,
    val nomerDogovora: String? = null,
    val dataDogovora: LocalDateTime? = null,
    val okpo: String? = null,
    val disabledagn: Long? = null,
    val disabledagngroup: Long? = null,
    val typeDog: Long? = null,
    val dataDogovoraEnd: LocalDateTime? = null,
    val dataSaleEnd: LocalDateTime? = null,
    val supplier: Long? = null,
    val leading: Long? = null,
    val shipper: Long? = null,
    val receiver: Long? = null,
    val dscgroup: Long? = null,
    val region: Long? = null,
    val consignee: Long? = null,
    val authRequire: Long? = null
){
    companion object {
        fun fromEntity(entity: AgnList): AgnListForUpdResponse {
            return AgnListForUpdResponse(
                rn = entity.rn,
                agncode = entity.agncode,
                agnname = entity.agnname,
                agnidnumb = entity.agnidnumb,
                reasonCode = entity.reasonCode,
                agntype = entity.agntype,
                addrFactpost = entity.addrFactpost,
                addrUrpost = entity.addrUrpost,
                fax = entity.fax,
                mail = entity.mail,
                bankaccname = entity.bankaccname,
                bankaccnumb = entity.bankaccnumb,
                bankaccbik = entity.bankaccbik,
                bankacckor = entity.bankacckor,
                passportSer = entity.passportSer,
                passportNumb = entity.passportNumb,
                passportWhen = entity.passportWhen,
                passportWho = entity.passportWho,
                agnContacts = entity.agnContacts,
                note = entity.note,
                business = entity.business,
                licence = entity.licence,
                typecard = entity.typecard,
                agngroup = entity.agngroup,
                enabled = entity.enabled,
                manager = entity.manager,
                cashlessDelay = entity.cashlessDelay,
                cashlessCredit = entity.cashlessCredit,
                phone = entity.phone,
                nomerDogovora = entity.nomerDogovora,
                dataDogovora = entity.dataDogovora,
                okpo = entity.okpo,
                disabledagn = entity.disabledagn,
                disabledagngroup = entity.disabledagngroup,
                typeDog = entity.typeDog,
                dataDogovoraEnd = entity.dataDogovoraEnd,
                dataSaleEnd = entity.dataSaleEnd,
                leading = entity.leading,
                shipper = entity.shipper,
                receiver = entity.receiver,
                dscgroup = entity.dscgroup,
                region = entity.region,
                consignee = entity.consignee,
                phonenumberrn = entity.phonenumberrn,
                authRequire = entity.authRequire
            )
        }
    }
}